name: Build Ionic Angular App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.19.0

      - name: Install Cordova and Ionic CLI
        run: npm install -g cordova ionic

      - name: Install project dependencies
        run: npm install

      - name: Build Ionic project
        run: npx ionic build

      - name: Archive Production Files (اختياري)
        uses: actions/upload-artifact@v3
        with:
          name: www-folder
          path: www




