name: Build and Prepare Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Ionic & Capacitor CLI
        run: npm install -g @ionic/cli @capacitor/cli

      - name: Install project dependencies
        run: npm install

      - name: Build Ionic project
        run: npm run build

      - name: Initialize Capacitor
        run: npx cap init "MyApp" "com.example.myapp" --web-dir=www --npm-client=npm

      - name: Add Android platform
        run: npx cap add android

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Upload Android project folder
        uses: actions/upload-artifact@v4
        with:
          name: android-folder
          path: android











