name: Build Ionic Angular App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout code
        uses: actions/checkout@v4

      - name: ✅ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1 # متوافق مع cordova-android

      - name: ✅ Install Ionic CLI and Capacitor
        run: |
          npm install -g @ionic/cli
          npm install

      - name: ✅ Build Ionic project
        run: npm run build || npx ionic build

      - name: ✅ Initialize Capacitor
        run: npx cap init "MyApp" "com.example.myapp" --web-dir=www

      - name: ✅ Add Android platform
        run: npm install @capacitor/android && npx cap add android

      - name: ✅ Copy web assets to native platforms
        run: npx cap copy

      - name: ✅ Upload Android folder
        uses: actions/upload-artifact@v4
        with:
          name: android-project
          path: android










